
variables:
  IMAGE_NAME: emcmongoose/darzee
  LATEST_IMAGE_TAG: latest
  TESTING_IMAGE_TAG: testing
  IMAGE_FILE_NAME: darzee.tar
  CREATED_DARZEE_DOCKERFILE_PATH: docker/Dockerfile
 
  # NOTE: Reassigning pre-defined variables 
  SERVICE_HOST: docker # should be used instead of the "localhost"/"127.0.0.1" in GL CI
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - create_dockerfile
  - build_docker_image
  - release_testing_image_to_docker_hub
  - release_latest_image_to_docker_hub

create_dockerfile:
  stage: create_dockerfile
  image: java:8-jdk
  artifacts:
    paths:
      - $CREATED_DARZEE_DOCKERFILE_PATH
  script:
    - ./gradlew clean createDockerfile

build_docker_image:
  stage: build_docker_image
  image: docker:stable
  script:
    - cp $CREATED_DARZEE_DOCKERFILE_PATH .
    - ls
    - docker build -t emcmongoose/darzee:latest .
    - docker save emcmongoose/darzee:latest > darzee.tar
    - echo $CI_COMMIT_SHA
    - echo $DOCKER_USER
  artifacts:
    paths:
      - darzee.tar

# NOTE: Releasing testing image into the docker hub. This is done in order to ...
# ... test Darzee's updated version in deployment environment before the release.
release_testing_image_to_docker_hub:
  stage: release_testing_image_to_docker_hub
  image: docker:stable
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker load < darzee.tar
    - docker tag $IMAGE_NAME $IMAGE_NAME:$LATEST_IMAGE_TAG
    - docker push $IMAGE_NAME:$LATEST_IMAGE_TAG

  only:
    - merge_requests

# NOTE: Releasing new Darzee version under tha "latest" tag only ...
# ... in case of merge into master.
release_latest_image_to_docker_hub:
  stage: release_latest_image_to_docker_hub
  image: docker:stable
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker load < darzee.tar
    - docker tag $IMAGE_NAME $IMAGE_NAME:$TESTING_IMAGE_TAG
    - docker push $IMAGE_NAME:$TESTING_IMAGE_TAG

  only:
    - master
