
variables:
  IMAGE_NAME: emcmongoose/darzee
  LATEST_IMAGE_TAG: latest
  TESTING_IMAGE_TAG: testing
  IMAGE_FILE_NAME: darzee.tar
  CREATED_DARZEE_DOCKERFILE_PATH: docker/Dockerfile
 
  # NOTE: Reassigning pre-defined variables 
  SERVICE_HOST: docker # should be used instead of the "localhost"/"127.0.0.1" in GL CI
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

stages:
  - create_dockerfile
  - build_docker_image
  - deploy

create_dockerfile:
  image: java:8-jdk
  stage: create_dockerfile
  artifacts:
    paths:
      - $CREATED_DARZEE_DOCKERFILE_PATH
  script:
    - ./gradlew clean createDockerfile

build_docker_image:
  image: docker:stable
  stage: build_docker_image
  script:
    - cp $CREATED_DARZEE_DOCKERFILE_PATH .
    - ls
    - docker build -t emcmongoose/darzee:latest .
    - docker save emcmongoose/darzee:latest > darzee.tar
    - echo $CI_COMMIT_SHA
    - echo $DOCKER_USER
  artifacts:
    paths:
      - darzee.tar

release_to_docker_hub:
  image: docker:stable
  stage: deploy
  script:
    - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - docker load < darzee.tar
    - docker tag $IMAGE_NAME:$CI_COMMIT_SHA $IMAGE_NAME:$MONGOOSE_VERSION
    - docker push $IMAGE_NAME:${LATEST_IMAGE_TAG}
    - docker tag ${IMAGE_NAME}:${LATEST_IMAGE_TAG}
    - docker push ${IMAGE_NAME}:${LATEST_IMAGE_TAG}

  only:
  # NOTE: Using GUI-47-continious-integration in test purposes 
  # TODO: Change target branch name to "master"
    - GUI-47-continious-integration
  except:
    - branches