version: '3'
services:
    darzee:
        image: 'emcmongoose/darzee:${DARZEE_VER}'
        network_mode: host
        ports:
            - '${DARZEE_PORT}:${DARZEE_PORT}'
        env_file:
            - .env
        volumes:
            - prometheus-configuration-folder-volume:${PROMETHEUS_CONFIGURATION_FOLDER_PATH}
            
    prometheus:
        image: 'prom/prometheus:${PROMETHEUS_VER}'
        network_mode: host
        ports:
            - '${PROMETHEUS_PORT}:${PROMETHEUS_PORT}'
        volumes:
            - prometheus-configuration-folder-volume:/etc/prometheus/
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.enable-lifecycle'
volumes:
    prometheus-configuration-folder-volume: 
