apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongoose-pravega
  name: mongoose-pravega-svc
spec:
  ports:
    # NOTE: Exposting ports
    - name: mongoose-pravega-port
    # NOTE: Remote API Port
      port: 9999
      targetPort: 9999
  selector:
    app: mongoose-pravega-svc
  type: LoadBalancer
  sessionAffinity: None
