apiVersion: v1
kind: Service
metadata:
  labels:
    app: darzee
  name: darzee-svc
spec:
  ports:
    # NOTE: Exposting ports
    - name: nodejs-server-port
      port: 8080
      targetPort: 8080
    - name: prometheus-port
      port: 9090
      targetPort: 9090
  selector:
    app: darzee
  type: LoadBalancer
  sessionAffinity: None
