apiVersion: apps/v1
kind: Service
metadata:
  labels:
    app: darzee
  name: darzee-svc
spec:
  type: LoadBalancer
  ports:
    # NOTE: Exposting ports
    - port: 8080
      targetPort: 8080
    - port: 9090
      targetPort: 9090
  selector:
    app: darzee
  sessionAffinity: None
