apiVersion: apps/v1
kind: Deployment
metadata:
  name: darzee-deployment
spec:
  selector:
    matchLabels:
      app: darzee
  replicas: 1 
  template:
    metadata:
      labels:
        app: darzee
    spec:
      containers:
      - name: darzee
        image: emcmongoose/darzee:latest
        ports:
        - containerPort: 80