apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongoose-base
  name: mongoose-base-dc
spec:
  selector:
    matchLabels:
      app: mongoose-base
  replicas: 1 
  template:
    metadata:
      labels:
        app: mongoose-base
    spec:
      containers:
      - name: mongoose-base-1
        image: emcmongoose/mongoose-base
        args: [--run-node, --storage-driver-type=dummy-mock, --run-port=9991, --load-step-node-port=9991]

      - name: mongoose-base-2
        image: emcmongoose/mongoose-base
        args: [--run-node, --storage-driver-type=dummy-mock, --run-port=9992, --load-step-node-port=9992]

      - name: mongoose-base-3
        image: emcmongoose/mongoose-base
        args: [--run-node, --storage-driver-type=dummy-mock, --run-port=9993, --load-step-node-port=9993]
     
      - name: mongoose-base-4
        image: emcmongoose/mongoose-base
        args: [--run-node, --storage-driver-type=dummy-mock, --run-port=9994, --load-step-node-port=9994]
      
      - name: mongoose-base-5
        image: emcmongoose/mongoose-base
        args: [--run-node, --storage-driver-type=dummy-mock, --run-port=9999, --load-step-node-port=9999]

       